export const newsArticles = [
  {
    id: "colic-vet-fee-dispute-2023",
    title: "Colic Surgery Fee Dispute: Owner v. Dealer",
    summary: "A dealer refused to pay for emergency colic surgery after a horse sold to a private owner fell ill within 10 days. The court ruled in favor of the buyer, citing the Consumer Rights Act 2015.",
    author: "FindMyHorse Team",
    content: [
      { type: 'paragraph', text: "In a landmark case that highlights the importance of consumer protection in horse sales, a dealer was found liable for veterinary costs after a horse developed severe colic within 10 days of purchase. The case, heard in Surrey County Court, involved a £7,000 emergency surgery bill and raised important questions about dealer responsibilities under the Consumer Rights Act 2015." },
      { type: 'subheading', text: "Case Background" },
      { type: 'paragraph', text: "The horse, a 7-year-old Irish Sport Horse, was purchased for £12,000 from a licensed dealer. The buyer, an experienced horse owner, arranged for a pre-purchase veterinary examination which showed no signs of underlying health issues. However, within 10 days of purchase, the horse developed severe colic requiring emergency surgery." },
      { type: 'subheading', text: "Legal Arguments" },
      { type: 'paragraph', text: "The dealer argued that the colic was an unforeseeable event and not related to the horse's condition at the time of sale. They claimed that the pre-purchase examination had been thorough and showed no predisposition to colic. The buyer's legal team countered that under the Consumer Rights Act 2015, goods (including horses) must be of satisfactory quality and fit for purpose at the time of sale." },
      { type: 'quote', text: "The court found that the timing of the colic episode, combined with veterinary evidence suggesting underlying digestive issues, indicated that the horse was not of satisfactory quality at the time of sale.", source: "Judge's Ruling" },
      { type: 'subheading', text: "Key Legal Principles" },
      { type: 'paragraph', text: "The case established several important principles for horse sales under consumer law: 1) Dealers have a higher duty of care than private sellers, 2) The timing of health issues can be crucial in determining liability, 3) Pre-purchase examinations do not absolve dealers of their responsibilities under consumer law." },
      { type: 'subheading', text: "Practical Implications" },
      { type: 'paragraph', text: "This case has significant implications for both buyers and sellers. Buyers should ensure they have comprehensive documentation of the horse's health history and any veterinary examinations. Dealers should maintain detailed records of veterinary care and be prepared to address health issues that arise shortly after sale." },
      { type: 'subheading', text: "Preventive Measures" },
      { type: 'paragraph', text: "To prevent similar disputes, dealers should: 1) Maintain comprehensive health records, 2) Consider offering short-term health guarantees, 3) Be transparent about any known health issues, 4) Have clear terms in their sales contracts regarding post-sale health issues." }
    ],
    outcome: "Dealer Liable for Vet Fees",
    amount: "£7,000",
    duration: "2 months",
    location: "Surrey",
    category: "Health Issues",
    featured: true,
    outcomeType: "positive"
  },
  {
    id: "misrepresentation-height-pony-2022",
    title: "Misrepresented Pony Height: Buyer Awarded Damages",
    summary: "A buyer was awarded damages after a pony was found to be 3 inches shorter than advertised, affecting its eligibility for competitions.",
    author: "FindMyHorse Team",
    content: [
      { type: 'paragraph', text: "A significant case in equine competition law saw a buyer successfully claim damages after discovering their show pony was significantly shorter than advertised. The case, which took place in Cheshire, highlighted the importance of accurate representation in horse sales, particularly for competition animals." },
      { type: 'subheading', text: "Case Details" },
      { type: 'paragraph', text: "The pony was advertised as 148cm, making it eligible for specific show classes. The buyer, a competitive show rider, paid £8,500 for the pony based on this height specification. However, during a competition veterinary check, the pony measured only 140cm, making it ineligible for the intended classes." },
      { type: 'subheading', text: "Legal Analysis" },
      { type: 'paragraph', text: "The court found that the height misrepresentation constituted a material breach of contract. The judge noted that height is a crucial factor in competition eligibility and directly affects a pony's value and intended use. The seller's failure to provide accurate measurements, whether intentional or negligent, constituted misrepresentation under the Misrepresentation Act 1967." },
      { type: 'quote', text: "In competition horses, accurate representation of key characteristics such as height is not merely a matter of preference but a fundamental aspect of the animal's value and utility.", source: "Court Judgment" },
      { type: 'subheading', text: "Damages Calculation" },
      { type: 'paragraph', text: "The court awarded £2,500 in damages, calculated based on: 1) The difference in market value between a 148cm and 140cm pony, 2) Lost competition opportunities, 3) Additional training costs incurred, 4) Transportation and competition entry fees that were wasted." },
      { type: 'subheading', text: "Industry Impact" },
      { type: 'paragraph', text: "This case has led to increased awareness of the importance of accurate height measurement in competition horses. Many show organizations now require official height certificates, and buyers are increasingly requesting independent height verification before purchase." },
      { type: 'subheading', text: "Preventive Measures" },
      { type: 'paragraph', text: "To avoid similar disputes, sellers should: 1) Obtain official height certificates, 2) Use qualified measurers, 3) Document measurements with photographs, 4) Include specific height warranties in sales contracts. Buyers should: 1) Request independent measurement, 2) Verify competition eligibility, 3) Include height-specific terms in purchase agreements." }
    ],
    outcome: "Damages Awarded",
    amount: "£2,500",
    duration: "4 months",
    location: "Cheshire",
    category: "Misrepresentation",
    featured: true,
    outcomeType: "positive"
  },
  {
    id: "dealer-fails-to-disclose-vices-2024",
    title: "Dealer Fails to Disclose Stable Vices: Full Refund Ordered",
    summary: "A horse sold by a dealer was found to have severe crib-biting and weaving vices. The buyer was granted a full refund after the court found non-disclosure.",
    author: "FindMyHorse Team",
    content: [
      { type: 'paragraph', text: "A recent case in Lancashire has set an important precedent regarding the disclosure of stable vices in horse sales. The court ordered a full refund of £5,500 after finding that a dealer had failed to disclose severe crib-biting and weaving behaviors in a horse sold to a private buyer." },
      { type: 'subheading', text: "Case Background" },
      { type: 'paragraph', text: "The horse, a 6-year-old Warmblood, was purchased from a licensed dealer. The buyer discovered severe crib-biting and weaving behaviors within days of the horse arriving at their yard. These vices were not mentioned in the sales documentation or during the viewing process." },
      { type: 'subheading', text: "Legal Arguments" },
      { type: 'paragraph', text: "The dealer argued that the vices developed after the sale due to the change in environment. However, veterinary evidence showed that the horse had been treated for dental issues consistent with long-term crib-biting. The court found that the dealer had a duty to disclose these vices under the Consumer Rights Act 2015." },
      { type: 'quote', text: "Stable vices that affect a horse's value, usability, or welfare must be disclosed to potential buyers. Non-disclosure constitutes a material breach of the duty to provide goods of satisfactory quality.", source: "Judge's Ruling" },
      { type: 'subheading', text: "Impact on Horse Value" },
      { type: 'paragraph', text: "The court heard expert testimony that stable vices can significantly reduce a horse's value and may affect its insurability. The vices in this case were severe enough to impact the horse's usability and required specialized management." },
      { type: 'subheading', text: "Legal Implications" },
      { type: 'paragraph', text: "This case reinforces that dealers must disclose all known vices and behavioral issues. The court found that the buyer had the right to expect the horse to be free from undisclosed vices that would affect its value or usability." },
      { type: 'subheading', text: "Preventive Measures" },
      { type: 'paragraph', text: "To prevent similar disputes, dealers should: 1) Document all known vices, 2) Include behavioral assessments in pre-purchase examinations, 3) Provide written disclosure of any behavioral issues, 4) Consider offering trial periods for buyers to observe the horse in their environment." }
    ],
    outcome: "Full Refund",
    amount: "£5,500",
    duration: "3 weeks",
    location: "Lancashire",
    category: "Misrepresentation",
    featured: false,
    outcomeType: "positive"
  },
  {
    id: "private-sale-lameness-2023",
    title: "Private Sale Lameness: Buyer Loses Claim",
    summary: "A private buyer failed to recover costs after a horse developed lameness post-sale. The court found no misrepresentation.",
    author: "FindMyHorse Team",
    content: [
      { type: 'paragraph', text: "A significant case in Kent highlighted the differences between private sales and dealer sales under UK law. The court dismissed a claim for damages after a horse developed lameness three weeks after a private sale, emphasizing the importance of understanding different legal protections in private transactions." },
      { type: 'subheading', text: "Case Details" },
      { type: 'paragraph', text: "The horse was sold privately for £4,000. The buyer arranged a pre-purchase examination which showed no signs of lameness. However, three weeks after purchase, the horse developed lameness in the right forelimb. The buyer sought to recover the purchase price and veterinary costs." },
      { type: 'subheading', text: "Legal Analysis" },
      { type: 'paragraph', text: "The court found that the seller had not made any false statements about the horse's health. The pre-purchase examination was thorough and showed no signs of lameness. The court noted that private sales are subject to different legal standards than dealer sales under the Consumer Rights Act 2015." },
      { type: 'quote', text: "In private sales, the principle of 'caveat emptor' (buyer beware) applies more strongly than in dealer sales. The buyer must prove that the seller made false statements or actively concealed issues.", source: "Court Judgment" },
      { type: 'subheading', text: "Key Legal Principles" },
      { type: 'paragraph', text: "This case established several important points: 1) Private sellers have fewer legal obligations than dealers, 2) The burden of proof is higher for buyers in private sales, 3) Pre-purchase examinations are crucial in private transactions, 4) Timing of health issues can be critical in determining liability." },
      { type: 'subheading', text: "Practical Implications" },
      { type: 'paragraph', text: "The case highlights the importance of: 1) Thorough pre-purchase examinations, 2) Clear documentation of the horse's health history, 3) Understanding the different legal protections in private vs. dealer sales, 4) Proper contract documentation in private transactions." },
      { type: 'subheading', text: "Preventive Measures" },
      { type: 'paragraph', text: "To protect themselves in private sales, buyers should: 1) Arrange comprehensive veterinary examinations, 2) Document all communications with the seller, 3) Consider including specific health warranties in the sales contract, 4) Be aware of the different legal protections in private sales." }
    ],
    outcome: "Claim Dismissed",
    amount: "£4,000",
    duration: "2 months",
    location: "Kent",
    category: "Health Issues",
    featured: false,
    outcomeType: "negative"
  }
]; 